CREATE TABLE `RESTART` (
`StudentID` INT(10) NOT NULL DEFAULT '0',
`StudentName` CHAR(52) NOT NULL DEFAULT '',
`RestartCity` CHAR(52) NOT NULL DEFAULT '',
`GraduationDate` DATE NOT NULL);

INSERT INTO `RESTART` VALUES ('1','John','London','1998-04-16');

INSERT INTO `RESTART` VALUES ('2','Alex','Paris','1994-04-10');

INSERT INTO `RESTART` VALUES ('3','Max','Berlin','1993-04-16');

INSERT INTO `RESTART` VALUES ('4','Mohammed','Geneva','1991-04-16');

INSERT INTO `RESTART` VALUES ('5','Ahmed','Frankfurt','2000-04-16');


CREATE TABLE `CLOUD_PRACTITIONER` (
`StudentID` INT(10) NOT NULL DEFAULT '0',
`CertificationDate` DATE NOT NULL);

INSERT INTO `CLOUD_PRACTITIONER` VALUES ('1','1998-04-16');

INSERT INTO `CLOUD_PRACTITIONER` VALUES ('2','1994-04-10');

INSERT INTO `CLOUD_PRACTITIONER` VALUES ('3','1993-04-16');

INSERT INTO `CLOUD_PRACTITIONER` VALUES ('4','1991-04-16');

INSERT INTO `CLOUD_PRACTITIONER` VALUES ('5','2000-04-16');


SELECT RESTART.StudentID, RESTART.StudentName, CLOUD_PRACTITIONER.CertificationDate
FROM RESTART
INNER JOIN CLOUD_PRACTITIONER ON RESTART.StudentID = CLOUD_PRACTITIONER.StudentID;
